version: 0.0
os: linux
files:
  - source: /
    destination: /home/rat/pi-api
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: rat
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: rat
  AfterInstall:
    - location: scripts/after_install.sh
      runas: rat
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: rat
